on:
  push:
    tags: ['v*.*.*']

jobs:
  build:
    name: Create release with release notes from changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: CSchoel/release-notes-from-changelog@v1
      # use GitHub CLI to create release
      # see https://cli.github.com/manual/gh_release_create
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          gh release create
          -p
          -F RELEASE.md
          -t "Version $RELEASE_VERSION"
          ${GITHUB_REF#refs/*/}
